unmarked:
  title: ラブライブ!
  unit: muse
  trio_units:
    - printemps
    - bibi
    - lily_white
  idols:
    - rin
    - hanayo
    - maki
    - honoka
    - umi
    - kotori
    - eli
    - nozomi
    - nico
    - tsubasa
    - erena
    - anju

sunshine:
  title: ラブライブ!サンシャイン!!
  unit: aqours
  trio_units:
    - cyaron
    - azalea
    - guilty_kiss
  idols:
    - yoshiko
    - hanamaru
    - ruby
    - chika
    - riko
    - you
    - kanan
    - dia
    - mari
    - sarah
    - lear
