printemps:
  name: Printemps
  idols:
    - hanayo
    - honoka
    - kotori

bibi:
  name: BiBi
  idols:
    - maki
    - eli
    - nico

lily_white:
  name: Lili White
  idols:
    - rin
    - umi
    - nozomi

cyaron:
  name: CYaRon!
  idols:
    - ruby
    - chika
    - you

azalea:
  name: AZALEA
  idols:
    - hanamaru
    - kanan
    - dia

guilty_kiss:
  name: Guilty Kiss
  idols:
    - yoshiko
    - riko
    - mari
