muse:
  name: μ’s
  idols:
    - rin
    - hanayo
    - maki
    - honoka
    - umi
    - kotori
    - eli
    - nozomi
    - nico

arise:
  name: A-RISE
  idols:
    - tsubasa
    - erena
    - annju

printemps:
  name: Printemps
  idols:
    - hanayo
    - honoka
    - kotori

bibi:
  name: BiBi
  idols:
    - maki
    - eli
    - nico

lily_white:
  name: Lili White
  idols:
    - rin
    - umi
    - nozomi

aqours:
  name: Aqours
  idols:
    - yoshiko
    - hanamaru
    - ruby
    - chika
    - riko
    - you
    - kanan
    - dia
    - mari

saint_snow:
  name: Saint Snow
  idols:
    - sarah
    - lear

cyaron:
  name: CYaRon!
  idols:
    - ruby
    - chika
    - you

azalea:
  name: AZALEA
  idols:
    - hanamaru
    - kanan
    - dia

guilty_kiss:
  name: Guilty Kiss
  idols:
    - yoshiko
    - riko
    - mari
